name: "Update GitHub Pages"

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: "Generate index.html"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
    - name: "Create Pages Archive"
      run: |
        mkdir -p _site
        python3 ascii.py > _site/index.html
    - name: "Upload Archive"
      uses: actions/upload-pages-artifact@v1

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: $
    needs: build
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v2
