name: "Update GitHub Pages

on:
  push:

jobs:
  build:
    name: "Generate index.html"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
    - name: "Create Pages Archive"
      run: |
        python3 ascii.py > index.html
        tar cf - index.html | gzip > github-pages.tar.gz
    - name: "Upload Archive"
      uses: actions/upload-pages-artifact@v1

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: $
    needs: build
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v1
