name: "Update GitHub Pages

on:
  push:

jobs:
  build:
    name: "Generate index.html"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Checkout gh-pages"
      uses: actions/checkout@v3
      args:
        ref: gh-pages
        fetch-depth: 0

    - name: "Update index.html"
      run: |
        python3 <(git show ${{ github.ref }}:ascii.py) > index.html
        git commit -m "Update index.html" index.html
        git push origin gh-pages
